linters:
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - ginkgolinter
    - goconst
    - gofmt
    - goheader
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - mnd
    - perfsprint
    - reassign
    - sqlclosecheck
    - staticcheck
    - unparam
    - unused
    - whitespace
issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gosec
linters-settings:
  goheader:
    template: |-
      Copyright (c) {{MOD-YEAR-RANGE}} David Ouellette.
      
      All rights reserved.
      
      This software and its documentation are proprietary information of David Ouellette.
      No part of this software or its documentation may be copied, transferred, reproduced,
      distributed, modified, or disclosed without the prior written permission of David Ouellette.
      
      Unauthorized use of this software is strictly prohibited and may be subject to civil and
      criminal penalties.
      
      By using this software, you agree to abide by the terms specified herein.
