apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default-namespace-deny
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - {}
  egress:
    - {}
